// <auto-generated />
using System;
using EcoSystem.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoSystem.Data.Migrations
{
    [DbContext(typeof(EcoSystemDbContext))]
    [Migration("20260618152430_CreateTiendaSchema")]
    partial class CreateTiendaSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoSystem.Data.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("categorias", "public");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Gadgets y dispositivos",
                            NombreCategoria = "Electrónica"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Prendas de vestir",
                            NombreCategoria = "Ropa"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Artículos para el hogar",
                            NombreCategoria = "Hogar"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Descripcion = "Literatura y técnicos",
                            NombreCategoria = "Libros"
                        });
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCliente");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("clientes", "public");

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            Ciudad = "CDMX",
                            Email = "ana@email.com",
                            FechaRegistro = new DateOnly(2023, 1, 15),
                            Nombre = "Ana García"
                        },
                        new
                        {
                            IdCliente = 2,
                            Ciudad = "Guadalajara",
                            Email = "luis@email.com",
                            FechaRegistro = new DateOnly(2023, 3, 22),
                            Nombre = "Luis Martínez"
                        },
                        new
                        {
                            IdCliente = 3,
                            Ciudad = "Monterrey",
                            Email = "maria@email.com",
                            FechaRegistro = new DateOnly(2023, 6, 10),
                            Nombre = "María López"
                        },
                        new
                        {
                            IdCliente = 4,
                            Ciudad = "CDMX",
                            Email = "carlos@email.com",
                            FechaRegistro = new DateOnly(2024, 1, 5),
                            Nombre = "Carlos Ruiz"
                        },
                        new
                        {
                            IdCliente = 5,
                            Ciudad = "Puebla",
                            FechaRegistro = new DateOnly(2024, 2, 20),
                            Nombre = "Sofía Torres"
                        });
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.DetalleOrden", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdOrden")
                        .HasColumnType("integer")
                        .HasColumnName("id_orden");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdOrden");

                    b.HasIndex("IdProducto");

                    b.ToTable("detalle_ordenes", "public");

                    b.HasData(
                        new
                        {
                            IdDetalle = 1,
                            Cantidad = 1,
                            IdOrden = 1,
                            IdProducto = 1,
                            PrecioUnitario = 18500.00m
                        },
                        new
                        {
                            IdDetalle = 2,
                            Cantidad = 2,
                            IdOrden = 1,
                            IdProducto = 2,
                            PrecioUnitario = 950.00m
                        },
                        new
                        {
                            IdDetalle = 3,
                            Cantidad = 3,
                            IdOrden = 2,
                            IdProducto = 3,
                            PrecioUnitario = 280.00m
                        },
                        new
                        {
                            IdDetalle = 4,
                            Cantidad = 1,
                            IdOrden = 3,
                            IdProducto = 4,
                            PrecioUnitario = 1200.00m
                        },
                        new
                        {
                            IdDetalle = 5,
                            Cantidad = 2,
                            IdOrden = 3,
                            IdProducto = 6,
                            PrecioUnitario = 350.00m
                        },
                        new
                        {
                            IdDetalle = 6,
                            Cantidad = 1,
                            IdOrden = 4,
                            IdProducto = 5,
                            PrecioUnitario = 22000.00m
                        },
                        new
                        {
                            IdDetalle = 7,
                            Cantidad = 1,
                            IdOrden = 5,
                            IdProducto = 2,
                            PrecioUnitario = 950.00m
                        });
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Orden", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_orden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrden"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_orden")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.HasKey("IdOrden");

                    b.HasIndex("IdCliente");

                    b.ToTable("ordenes", "public");

                    b.HasData(
                        new
                        {
                            IdOrden = 1,
                            Estado = "Entregado",
                            FechaOrden = new DateTime(2024, 1, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            IdCliente = 1
                        },
                        new
                        {
                            IdOrden = 2,
                            Estado = "Enviado",
                            FechaOrden = new DateTime(2024, 2, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            IdCliente = 1
                        },
                        new
                        {
                            IdOrden = 3,
                            Estado = "Entregado",
                            FechaOrden = new DateTime(2024, 1, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            IdCliente = 2
                        },
                        new
                        {
                            IdOrden = 4,
                            Estado = "Pendiente",
                            FechaOrden = new DateTime(2024, 3, 1, 16, 45, 0, 0, DateTimeKind.Utc),
                            IdCliente = 3
                        },
                        new
                        {
                            IdOrden = 5,
                            Estado = "Cancelado",
                            FechaOrden = new DateTime(2024, 3, 10, 11, 20, 0, 0, DateTimeKind.Utc),
                            IdCliente = 2
                        });
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("productos", "public");

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            IdCategoria = 1,
                            Nombre = "Laptop Pro 15",
                            Precio = 18500.00m,
                            Stock = 10
                        },
                        new
                        {
                            IdProducto = 2,
                            IdCategoria = 1,
                            Nombre = "Teclado Mecánico",
                            Precio = 950.00m,
                            Stock = 25
                        },
                        new
                        {
                            IdProducto = 3,
                            IdCategoria = 2,
                            Nombre = "Playera Casual",
                            Precio = 280.00m,
                            Stock = 100
                        },
                        new
                        {
                            IdProducto = 4,
                            IdCategoria = 3,
                            Nombre = "Cafetera Espresso",
                            Precio = 1200.00m,
                            Stock = 15
                        },
                        new
                        {
                            IdProducto = 5,
                            IdCategoria = 1,
                            Nombre = "Cámara Mirrorless",
                            Precio = 22000.00m,
                            Stock = 5
                        },
                        new
                        {
                            IdProducto = 6,
                            IdCategoria = 4,
                            Nombre = "SQL para Todos",
                            Precio = 350.00m,
                            Stock = 40
                        },
                        new
                        {
                            IdProducto = 7,
                            IdCategoria = 1,
                            Nombre = "Auriculares BT",
                            Precio = 1500.00m,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.DetalleOrden", b =>
                {
                    b.HasOne("EcoSystem.Data.Entities.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EcoSystem.Data.Entities.Producto", "Producto")
                        .WithMany("DetallesOrdenes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Orden", b =>
                {
                    b.HasOne("EcoSystem.Data.Entities.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Producto", b =>
                {
                    b.HasOne("EcoSystem.Data.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("EcoSystem.Data.Entities.Producto", b =>
                {
                    b.Navigation("DetallesOrdenes");
                });
#pragma warning restore 612, 618
        }
    }
}
