@EcoSystem.API_HostAddress = https://localhost:7196

GET {{EcoSystem.API_HostAddress}}/swagger

###

GET {{EcoSystem.API_HostAddress}}/api/categorias

###

POST {{EcoSystem.API_HostAddress}}/api/categorias
Content-Type: application/json

{
  "nombreCategoria": "Accesorios",
  "descripcion": "Productos complementarios"
}

###

GET {{EcoSystem.API_HostAddress}}/api/productos

###

POST {{EcoSystem.API_HostAddress}}/api/clientes
Content-Type: application/json

{
  "nombre": "Cliente de prueba",
  "email": "cliente@demo.com",
  "ciudad": "CDMX",
  "fechaRegistro": "2026-06-21"
}
